import type {PropType} from "vue";

export const IconName = 'd-icon'

const name = [
    "",
    "alert",
    "bell",
    "bookmark",
    "calendar",
    "camera",
    "cart",
    "clock",
    "close",
    "cloud",
    "comment",
    "copy",
    "delete",
    "dislike_thumb",
    "download",
    "edit",
    "emoji",
    "error",
    "export",
    "eye_closed_solid",
    "eye_opened",
    "female",
    "filter",
    "flag",
    "gift",
    "github",
    "help",
    "history",
    "home",
    "id_card",
    "image",
    "import",
    "info",
    "key",
    "like_thumb",
    "link",
    "list",
    "live",
    "location",
    "lock",
    "love",
    "mail",
    "male",
    "maximize",
    "minimize",
    "print",
    "qr_code",
    "safe",
    "scan",
    "search",
    "send",
    "setting",
    "shopping_bag",
    "spin",
    "star",
    "success",
    "tag",
    "terminal",
    "unlink",
    "unlock",
    "upload",
] as const;

export const IconProps = {
    name: {
        type: String as PropType<typeof name[number]>,
        default: "",
    },
    size: {
        type: String,
        default: "14px",
    },
    color: {
        type: String,
        default: "#3c3c3c",
    },
    spin: {
        type: Boolean,
        default: false,
    },
}